#api call for addition two number
###
POST http://127.0.0.1:8000/addition/
Content-Type: application/json

{
    "num1":15,
    "num2":25
}

#api call for substration
###
POST http://127.0.0.1:8000/substraction/
Content-Type: application/json

{
    "num1":50,
    "num2":18
}

#api call for multiplication
### 
POST http://127.0.0.1:8000/multiplication/
Content-Type: application/json

{
    "num1":12,
    "num2":4
}

#api call for division
###
POST http://127.0.0.1:8000/division/
Content-Type: application/json

{
    "num1":100,
    "num2":4
}

#api call for factorial
###
POST http://127.0.0.1:8000/factorial/
Content-Type: application/json

{
    "num1":5
}

#api call for prime number
###
POST http://127.0.0.1:8000/prime/
Content-Type: application/json

{
    "num1":29
}

#api call for perfect number
###
POST http://127.0.0.1:8000/perfect/
Content-Type: application/json

{
    "num1":28
}